### ISSUE TITLE
Installation notes: make sure to install gsl

### ISSUE THREAD

**Issue by allenjromano** [Jpowell94/dhtk#1]
Just a note in case anyone has trouble with this. The topicmodels package depends on gsl. http://www.gnu.org/software/gsl/

For Ubuntu, for example, you will need to sudo apt-get install gsl-bin libgsl0-dev

**Comment by Jpowell94** [comment]
If you try installing using only the packages I specify in the travis yml, are you able to?

**Comment by Jpowell94** [comment]
I have added special instructions for linux users to the README, and I am going to mark this as closed.
